import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import { Suspense } from "react";
import Error from "./error";
import Loading from "./loading";
import NotFound from "./not-found";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <h1 className="text-center">Bienvenue sur ce chat !</h1>
        <div className="d-flex align-items-center vh-100">
          <div className="container">
            <ErrorBoundary fallback={<Error />}>
              <Suspense fallback={<Loading />}>
                <ErrorBoundary fallback={<NotFound />}>
                  {children}
                </ErrorBoundary>
              </Suspense>
            </ErrorBoundary>
          </div>
        </div>
      </body>
    </html>
  );
}
